const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")                          
const { zodToJsonSchema } = require("zod-to-json-schema")
const { normalizeInterviewReport } = require("./interviewReportNormalizer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})

const interviewReportSchema = z.object({
    matchScore: z.number().min(0).max(100).describe("A score between 0 and 100 indicating how well the candidate's resume matches the job description, with 100 being a perfect match"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question asked in the interview"),
        intention: z.string().describe("The intention behind asking the technical question"),
        answer: z.string().describe("The ideal answer to the technical question and what points the candidate should cover in their answer")
    })).min(5).describe("A list of technical questions asked in the interview along with their intention and ideal answer"),

    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral question asked in the interview"),
        intention: z.string().describe("The intention behind asking the behavioral question"),
        answer: z.string().describe("The ideal answer to the behavioral question")
    })).min(5).describe("A list of behavioral questions asked in the interview along with their intention and ideal answer"),

    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill that the candidate is lacking based on their resume and the job description"),
        severity: z.enum(["low","medium","high"]).describe("The severity of the skill gap")
    })).min(3).describe("A list of skill gaps identified for the candidate based on their resume and the job description"),

    preparationPlan: z.array(z.object({
        day: z.number().int().positive().describe("The day number in the preparation plan"),
        focus: z.string().describe("The main focus area for that day of preparation"),
        tasks: z.string().describe("The specific tasks the candidate should do on that day to prepare for the interview")
    })).min(5).describe("A day-wise preparation plan for the candidate to improve their chances of success in the interview")

}).describe("The schema for the interview report generated by the AI, including technical questions, behavioral questions, skill gaps, and a preparation plan")

async function generateInterviewReport(jobDescription, resume, selfDescription){
    const prompt = `You are an expert technical interviewer. Based on the following job description, candidate resume and self description, generate a comprehensive interview report. The report should include:
    Resume: ${resume}
    Self Description: ${selfDescription}
    Job Description: ${jobDescription}

    STRICT RULES:
    1) technicalQuestions must include exactly 5 items.
    2) behavioralQuestions must include exactly 5 items.
    3) skillGaps must include at least 3 items.
    4) preparationPlan must include exactly 5 day-wise items.
    5) Never return empty arrays.
    `

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config:{
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(interviewReportSchema)
        }
    })

    const parsed = JSON.parse(response.text)
    const normalized = normalizeInterviewReport(parsed)
    const validated = interviewReportSchema.safeParse(normalized)

    if (!validated.success) {
        throw new Error("AI returned invalid interview report format. Please try again.")
    }

    return validated.data                  
}

module.exports = { generateInterviewReport, interviewReportSchema }  