const { GoogleGenAI } = require("@google/genai")
const { z } = require("zod")                          
const { zodToJsonSchema } = require("zod-to-json-schema")
const { normalizeInterviewReport } = require("./interviewReportNormalizer")

const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})

const interviewReportSchema = z.object({
    matchScore: z.number().min(0).max(100).describe("A score between 0 and 100 indicating how well the candidate's resume matches the job description, with 100 being a perfect match"),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("The technical question asked in the interview"),
        intention: z.string().describe("The intention behind asking the technical question"),
        answer: z.string().describe("The ideal answer to the technical question and what points the candidate should cover in their answer")
    })).min(5).describe("A list of technical questions asked in the interview along with their intention and ideal answer"),

    behavioralQuestions: z.array(z.object({
        question: z.string().describe("The behavioral question asked in the interview"),
        intention: z.string().describe("The intention behind asking the behavioral question"),
        answer: z.string().describe("The ideal answer to the behavioral question")
    })).min(5).describe("A list of behavioral questions asked in the interview along with their intention and ideal answer"),

    skillGaps: z.array(z.object({
        skill: z.string().describe("The skill that the candidate is lacking based on their resume and the job description"),
        severity: z.enum(["low","medium","high"]).describe("The severity of the skill gap")
    })).min(3).describe("A list of skill gaps identified for the candidate based on their resume and the job description"),

    preparationPlan: z.array(z.object({
        day: z.number().int().positive().describe("The day number in the preparation plan"),
        focus: z.string().describe("The main focus area for that day of preparation"),
        tasks: z.string().describe("The specific tasks the candidate should do on that day to prepare for the interview")
    })).min(5).describe("A day-wise preparation plan for the candidate to improve their chances of success in the interview")

}).describe("The schema for the interview report generated by the AI, including technical questions, behavioral questions, skill gaps, and a preparation plan")

const tailoredResumeSchema = z.object({
    targetJobTitle: z.string().min(2).describe("The most suitable target job title for this candidate"),
    summary: z.string().min(20).describe("A concise professional summary aligned with target job"),
    skills: z.array(z.string().min(2)).min(6).max(15).describe("Key skills suitable for the target job"),
    experienceHighlights: z.array(z.string().min(10)).min(3).max(6).describe("Impact-focused experience bullet points"),
    professionalExperience: z.array(z.object({
        role: z.string().min(2),
        organization: z.string().min(2),
        duration: z.string().min(3),
        highlights: z.array(z.string().min(8)).min(2).max(5)
    })).max(4).default([]),
    projects: z.array(z.object({
        name: z.string().min(2),
        description: z.string().min(10),
        technologies: z.array(z.string().min(2)).min(1).max(8)
    })).min(2).max(4),
    education: z.array(z.string().min(4)).min(1).max(3),
    certifications: z.array(z.string().min(3)).max(5).default([])
}).describe("A job-targeted resume generated from interview performance and candidate profile")

const voiceInterviewTurnSchema = z.object({
    feedback: z.string().min(20).describe("Short evaluation of the candidate's spoken answer"),
    score: z.number().min(0).max(10).describe("Answer quality score from 0 to 10"),
    followUp: z.string().min(10).describe("A short follow-up or next interviewer message"),
    nextQuestion: z.string().min(10).optional().describe("Next question to ask if the interview should continue"),
    isComplete: z.boolean().describe("Whether the voice interview should end")
}).describe("A single voice interview turn response with evaluation and next step")

function normalizeVoiceTurnFeedback(turn) {
    const safeTurn = turn || {}
    const normalizedScore = Number.isFinite(Number(safeTurn.score)) ? Number(safeTurn.score) : 0
    const feedbackText = String(safeTurn.feedback || "").trim()
    const followUpText = String(safeTurn.followUp || "").trim()

    // For clearly weak/incorrect answers, avoid encouraging phrases and move forward.
    if (normalizedScore <= 4) {
        const correctedFeedback = feedbackText
            ? feedbackText.replace(/on the right track/gi, "not correct for this question")
            : "This answer is not correct for the question. Focus on the core concept and one relevant example next time."

        return {
            ...safeTurn,
            feedback: correctedFeedback,
            followUp: "Let's move to the next question.",
            score: normalizedScore
        }
    }

    return {
        ...safeTurn,
        feedback: feedbackText || "Thanks for your response.",
        followUp: followUpText || "Let's move to the next question.",
        score: normalizedScore
    }
}

function extractKeywords(text = "", limit = 6) {
    const stopWords = new Set([
        "the", "and", "for", "with", "that", "this", "you", "your", "are", "from",
        "have", "has", "will", "using", "job", "role", "work", "skills", "skill",
        "experience", "team", "teams", "year", "years", "must", "required", "need"
    ])

    const words = String(text)
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, " ")
        .split(/\s+/)
        .map((word) => word.trim())
        .filter((word) => word.length >= 3 && !stopWords.has(word))

    const counts = new Map()
    for (const word of words) {
        counts.set(word, (counts.get(word) || 0) + 1)
    }

    return [...counts.entries()]
        .sort((a, b) => b[1] - a[1])
        .slice(0, limit)
        .map(([word]) => word)
}

function titleCase(text = "") {
    return String(text)
        .split(/\s+/)
        .filter(Boolean)
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(" ")
}

function calculateDeterministicRoleFit(jobDescription = "", resume = "", selfDescription = "") {
    const jdKeywords = extractKeywords(jobDescription, 24)
    const profileKeywords = extractKeywords(`${resume}\n${selfDescription}`, 40)

    if (!jdKeywords.length || !profileKeywords.length) {
        return 60
    }

    const jdSet = new Set(jdKeywords)
    const profileSet = new Set(profileKeywords)
    let overlap = 0
    for (const token of jdSet) {
        if (profileSet.has(token)) overlap += 1
    }

    const overlapRatio = overlap / jdSet.size

    // Base + overlap coverage keeps score stable without inflating weak matches.
    const baseScore = 35
    const overlapContribution = overlapRatio * 60

    // Small confidence boost when candidate profile has enough signal words.
    const profileDepthBoost = profileSet.size >= 12 ? 5 : profileSet.size >= 8 ? 3 : 0

    return Math.max(0, Math.min(100, Math.round(baseScore + overlapContribution + profileDepthBoost)))
}

function reconcileRoleFitScore({ aiScore, jobDescription, resume, selfDescription }) {
    const deterministic = calculateDeterministicRoleFit(jobDescription, resume, selfDescription)
    const aiNumeric = Number(aiScore)

    if (!Number.isFinite(aiNumeric)) {
        return deterministic
    }

    const gap = Math.abs(aiNumeric - deterministic)
    const aiWeight = gap >= 35 ? 0.2 : 0.4
    const deterministicWeight = 1 - aiWeight
    return Math.max(0, Math.min(100, Math.round(aiNumeric * aiWeight + deterministic * deterministicWeight)))
}

function buildFallbackInterviewReport(jobDescription = "", resume = "", selfDescription = "") {
    const keywords = extractKeywords(`${jobDescription}\n${resume}\n${selfDescription}`, 8)
    const primarySkill = keywords[0] || "JavaScript"
    const secondarySkill = keywords[1] || "React"
    const tertiarySkill = keywords[2] || "Node.js"
    const scoreSeed = calculateDeterministicRoleFit(jobDescription, resume, selfDescription)

    const technicalQuestions = [
        {
            question: `How have you used ${titleCase(primarySkill)} in a real project?`,
            intention: "Check hands-on experience with the most relevant stack keyword.",
            answer: `Explain a project where you applied ${titleCase(primarySkill)} and mention the outcome.`
        },
        {
            question: `How do you structure and debug a ${titleCase(secondarySkill)} application?`,
            intention: "Assess frontend architecture and troubleshooting skills.",
            answer: "Describe component structure, state flow, and how you isolate bugs with logs or devtools."
        },
        {
            question: `What is your approach to building and securing APIs with ${titleCase(tertiarySkill)}?`,
            intention: "Test backend design and API security awareness.",
            answer: "Talk about routing, validation, authentication, and error handling with examples."
        },
        {
            question: `How do you handle data flow between client and server in a full-stack app?`,
            intention: "Measure full-stack understanding and integration experience.",
            answer: "Explain request/response flow, state management, and how you manage failures."
        },
        {
            question: `How do you improve the performance of a production web application?`,
            intention: "Check practical performance and optimization thinking.",
            answer: "Mention reducing re-renders, caching, lazy loading, and backend query optimization."
        }
    ]

    const behavioralQuestions = [
        {
            question: "Tell me about a time you had to learn a tool or concept quickly.",
            intention: "Assess adaptability and self-learning.",
            answer: "Use STAR format and focus on how quickly you became productive."
        },
        {
            question: "Describe a time you worked through a difficult bug or production issue.",
            intention: "Evaluate problem solving under pressure.",
            answer: "Show the steps you took, what you found, and the final result."
        },
        {
            question: "How do you communicate progress when a task is blocked?",
            intention: "Check collaboration and communication habits.",
            answer: "Explain how you share status early, ask for help, and keep stakeholders informed."
        },
        {
            question: "Tell me about a project you are proud of and your role in it.",
            intention: "Learn about ownership and impact.",
            answer: "Highlight the problem, your contribution, and the measurable result."
        },
        {
            question: "How do you prioritize tasks when you have multiple deadlines?",
            intention: "Assess planning and time management.",
            answer: "Talk about impact, urgency, and how you keep work visible and organized."
        }
    ]

    const skillGaps = keywords.slice(0, 3).map((skill, index) => ({
        skill: titleCase(skill),
        severity: index === 0 ? "high" : index === 1 ? "medium" : "low"
    }))

    while (skillGaps.length < 3) {
        skillGaps.push({
            skill: `Skill gap ${skillGaps.length + 1}`,
            severity: skillGaps.length === 0 ? "high" : "medium"
        })
    }

    return {
        matchScore: scoreSeed,
        technicalQuestions,
        behavioralQuestions,
        skillGaps,
        preparationPlan: [
            { day: 1, focus: "Review role requirements", tasks: "Read the job description and map it to your strongest project examples." },
            { day: 2, focus: "Practice technical fundamentals", tasks: "Revise the core stack, data flow, API design, and debugging patterns." },
            { day: 3, focus: "Strengthen project stories", tasks: "Prepare STAR answers for at least three projects or achievements." },
            { day: 4, focus: "Mock interview practice", tasks: "Answer common questions out loud and time your responses." },
            { day: 5, focus: "Final review", tasks: "Review weak areas, calm your delivery, and practice a short self-introduction." }
        ]
    }
}

function buildFallbackResumeData({ report, jobDescription = "", resume = "", selfDescription = "", voiceInterviewTurns = [], performanceScore = null }) {
    const keywords = extractKeywords(`${jobDescription}\n${resume}\n${selfDescription}\n${voiceInterviewTurns.map((turn) => turn.userAnswer).join(" ")}`, 8)
    const targetJobTitle = report?.title || `${titleCase(keywords.slice(0, 3).join(" ")) || "Software Engineer"}`.trim()

    return {
        targetJobTitle,
        summary: `Motivated candidate with a background aligned to ${targetJobTitle}. Interview performance score: ${performanceScore ?? report?.matchScore ?? "N/A"}. Focused on building practical solutions, clear communication, and steady execution.`,
        skills: Array.from(new Set([...keywords, "Communication", "Problem Solving", "Debugging", "Teamwork", "API Integration", "Git"]).values()).slice(0, 10),
        experienceHighlights: [
            `Built and improved features related to ${keywords[0] || "web applications"} with a focus on reliability and usability.`,
            "Worked across the full stack to connect front-end interactions with back-end APIs.",
            "Used interview feedback to identify strengths and improve communication and technical clarity."
        ],
        professionalExperience: [],
        projects: [
            {
                name: `${titleCase(keywords[0] || "Core") || "Core"} Application`,
                description: `An application centered on ${keywords[0] || "full-stack"} workflow and practical user experience.`,
                technologies: [keywords[0] || "JavaScript", keywords[1] || "React", keywords[2] || "Node.js"]
            },
            {
                name: "Interview Preparation Platform",
                description: "An AI-guided interview preparation workflow with resume analysis, question generation, and feedback.",
                technologies: ["React", "Express", "MongoDB"]
            }
        ],
        education: ["Relevant coursework or degree information"],
        certifications: []
    }
}

async function generateInterviewReport(jobDescription, resume, selfDescription){
    try {
        const prompt = `You are an expert technical interviewer. Based on the following job description, candidate resume and self description, generate a comprehensive interview report. The report should include:
        Resume: ${resume}
        Self Description: ${selfDescription}
        Job Description: ${jobDescription}

        STRICT RULES:
        1) technicalQuestions must include exactly 5 items.
        2) behavioralQuestions must include exactly 5 items.
        3) skillGaps must include at least 3 items.
        4) preparationPlan must include exactly 5 day-wise items.
        5) Never return empty arrays.
        `

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config:{
                responseMimeType: "application/json",
                responseSchema: zodToJsonSchema(interviewReportSchema)
            }
        })

        const parsed = JSON.parse(response.text)
        const normalized = normalizeInterviewReport(parsed)
        const validated = interviewReportSchema.safeParse(normalized)

        if (!validated.success) {
            console.warn("AI returned invalid interview report format. Falling back to deterministic report.")
            return buildFallbackInterviewReport(jobDescription, resume, selfDescription)
        }

        return {
            ...validated.data,
            matchScore: reconcileRoleFitScore({
                aiScore: validated.data.matchScore,
                jobDescription,
                resume,
                selfDescription
            })
        }
    } catch (error) {
        console.warn("generateInterviewReport failed, using fallback report:", error.message)
        return buildFallbackInterviewReport(jobDescription, resume, selfDescription)
    }
}

async function generateTailoredResumeData({ report, jobDescription, resume, selfDescription, voiceInterviewTurns = [], performanceScore = null }) {
    try {
        const interviewHighlights = Array.isArray(voiceInterviewTurns)
            ? voiceInterviewTurns.slice(0, 5).map((turn) => `Q: ${turn.question}\nA: ${turn.userAnswer}\nFeedback: ${turn.feedback}\nScore: ${turn.score}/10`).join("\n\n")
            : ""

        const prompt = `You are an expert technical recruiter and resume writer.
Create a polished resume draft for the candidate based on interview performance, the candidate's spoken answers, and the role.

Candidate resume text:
${resume}

Candidate self description:
${selfDescription}

Original job description:
${jobDescription}

Interview performance summary:
- Match score: ${report?.matchScore}
- Voice interview score: ${performanceScore ?? "N/A"}
- Skill gaps: ${(report?.skillGaps || []).map((item) => `${item.skill} (${item.severity})`).join(", ")}

Voice interview answers and feedback:
${interviewHighlights || "No voice interview answers were provided."}

Rules:
1) Keep content truthful and realistic from provided context.
2) Emphasize strengths and suitable role direction.
3) Use concise, ATS-friendly language.
4) Prefer strong action verbs and measurable impact in bullets.
5) Incorporate interview answers as proof points where relevant, but do not invent experience.
6) professionalExperience can be empty if no reliable company history is available.
7) Return valid JSON only matching schema.`

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: zodToJsonSchema(tailoredResumeSchema)
            }
        })

        const parsed = JSON.parse(response.text)
        const validated = tailoredResumeSchema.safeParse(parsed)
        if (!validated.success) {
            return buildFallbackResumeData({ report, jobDescription, resume, selfDescription, voiceInterviewTurns, performanceScore })
        }

        return validated.data
    } catch (error) {
        console.warn("generateTailoredResumeData failed, using fallback resume:", error.message)
        return buildFallbackResumeData({ report, jobDescription, resume, selfDescription, voiceInterviewTurns, performanceScore })
    }
}

async function generateVoiceInterviewTurn({ report, currentQuestion, answer, questionIndex, totalQuestions }) {
    try {
        const prompt = `You are a professional technical interviewer conducting a voice interview.
Evaluate the candidate's answer honestly and briefly.

Interview context:
- Role fit score: ${report?.matchScore}
- Skill gaps: ${(report?.skillGaps || []).map((item) => `${item.skill} (${item.severity})`).join(", ")}
- Current question ${questionIndex + 1} of ${totalQuestions}: ${currentQuestion}
- Candidate answer: ${answer}

Rules:
1) feedback should be concise, practical, and interview-like.
2) score must be from 0 to 10.
3) followUp should sound like a real interviewer response.
4) If the answer is clearly wrong or off-topic, feedback must explicitly say it is incorrect (do not say "right track").
5) For wrong answers, followUp must move to the next question and must not ask the candidate to retry the same question.
6) If this is the last question, set isComplete true and nextQuestion empty or omitted.
7) Return valid JSON only matching schema.`

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash",
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: zodToJsonSchema(voiceInterviewTurnSchema)
            }
        })

        const parsed = JSON.parse(response.text)
        const validated = voiceInterviewTurnSchema.safeParse(parsed)
        if (!validated.success) {
            throw new Error("AI returned invalid voice interview response. Please try again.")
        }

        return normalizeVoiceTurnFeedback(validated.data)
    } catch (error) {
        console.warn("generateVoiceInterviewTurn failed, using fallback turn:", error.message)
        return {
            feedback: "This answer is not correct for the question. Review the core concept and answer more directly.",
            score: 3,
            followUp: "Let's move to the next question.",
            nextQuestion: questionIndex + 1 >= totalQuestions ? undefined : `Let's move to the next question: ${currentQuestion}`,
            isComplete: questionIndex + 1 >= totalQuestions
        }
    }
}

module.exports = {
    generateInterviewReport,
    generateTailoredResumeData,
    generateVoiceInterviewTurn,
    reconcileRoleFitScore,
    interviewReportSchema,
    tailoredResumeSchema,
    voiceInterviewTurnSchema
}